### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by timeflying** [google/GTMAppAuth#31]
Safari cannot open the page because the address is invalid
![simulator screen shot 2017 4 19 10 13 44](https://cloud.githubusercontent.com/assets/6119146/25184979/8e74dee4-254e-11e7-82a0-39e7ea249d11.png)

**Comment by StevenEWright** [comment]
Is it possible you're getting this because you haven't handled the URL callback scheme?

**Comment by timeflying** [comment]
```
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
  // Sends the URL to the current authorization flow (if any) which will
  // process it if it relates to an authorization response.
  if ([_currentAuthorizationFlow resumeAuthorizationFlowWithURL:url]) {
    _currentAuthorizationFlow = nil;
    return YES;
  }

  // Your additional URL handling (if any) goes here.

  return NO;
}
```
I just paste above code on my delegate . Is that wrong?

**Comment by StevenEWright** [comment]
Nice! That's definitely necessary, but probably not enough on it's own.

Take a look at the iOS example app's [README.md](https://github.com/google/GTMAppAuth/tree/master/Example-iOS) here: [https://github.com/google/GTMAppAuth/tree/master/Example-iOS](https://github.com/google/GTMAppAuth/tree/master/Example-iOS)

It describes the other things you need to do to get the example app configured for handling Google's OAuth callback (which I assume is a good start for you since your screenshot shows Google in the background?). If you're not using Google you may have to tweak some things. But the general idea is as follows:

At the end of the sequence of events which occurs in the browser, there is one final redirect: a redirect back to the application itself. The URL it's trying to load is something like: YourBundleID://somePath...

The error you're seeing ("... the address is invalid.") is because the browser doesn't know what to do with the "YourBundleID" scheme (notice, it's not "http" or "https", etc). This would occur if your application doesn't register the custom scheme with iOS correctly.

Fortunately it's a simple problem to fix. It's just a small setting in your Info.plist file.

Apple's documentation is here: [https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html#//apple_ref/doc/uid/TP40007072-CH6-SW10 ](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html#//apple_ref/doc/uid/TP40007072-CH6-SW10 )

Twitter has a nice page with screenshots of how to do it through XCode: [https://dev.twitter.com/cards/mobile/url-schemes](https://dev.twitter.com/cards/mobile/url-schemes)

Let me know if that's enough to get you going, or if you're still stuck.

**Comment by timeflying** [comment]
Thank you very much for your great explanation!
After open the Info.plist and fully expand "URL types" then add the reverse DNS notation form of my client id the problem is gone. Thank you!! 

But could you please tell me why the call back function always into the 
```
(BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options 
```
instead of the following code ?
```
appDelegate.currentAuthorizationFlow =
    [OIDAuthState authStateByPresentingAuthorizationRequest:request
                                   presentingViewController:self
                                                   callback:^(OIDAuthState *_Nullable authState,
                                                              NSError *_Nullable error)
    {
      if (authState) {
        GTMAppAuthFetcherAuthorization *authorization =
        [[GTMAppAuthFetcherAuthorization alloc] initWithAuthState:authState];
        
        [self setGtmAuthorization:authorization];
        [self logMessage:@"Got authorization tokens. Access token: %@",
         authState.lastTokenResponse.accessToken];
        [self finishedWithAuth:authorization
                     authState: authState
                         error:(NSError *)error];
      } else {
        [self setGtmAuthorization:nil];
        [self logMessage:@"Authorization error: %@", [error localizedDescription]];
      }
    }];
  }];
```
But after the

**Comment by timeflying** [comment]
Could you please tell me why the authState in the following code  is   nil?
```
appDelegate.currentAuthorizationFlow =
    [OIDAuthState authStateByPresentingAuthorizationRequest:request
                                   presentingViewController:self
                                                   callback:^(OIDAuthState *_Nullable authState,
                                                              NSError *_Nullable error)
    {
      if (authState) {
        GTMAppAuthFetcherAuthorization *authorization =
        [[GTMAppAuthFetcherAuthorization alloc] initWithAuthState:authState];
        
        [self setGtmAuthorization:authorization];
        [self logMessage:@"Got authorization tokens. Access token: %@",
         authState.lastTokenResponse.accessToken];
        [self finishedWithAuth:authorization
                     authState: authState
                         error:(NSError *)error];
      } else {
        [self setGtmAuthorization:nil];
        [self logMessage:@"Authorization error: %@", [error localizedDescription]];
      }
    }];
```

**Comment by StevenEWright** [comment]
Glad to hear it! I'll go ahead and close this issue!

**Comment by vidit011** [comment]
The links in my webpage are not opening. They are showing an error that safari cannot open because of invalid address https://vidit011.github.io/CV/
